2024-01-21 19:05:48,683 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:05:49,135 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getMe HTTP/1.1" 200 189
2024-01-21 19:05:49,138 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:06:09,496 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:06:29,557 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:06:49,623 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:09:36,676 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:09:37,263 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getMe HTTP/1.1" 200 189
2024-01-21 19:09:37,265 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:09:46,080 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 359
2024-01-21 19:09:46,080 - root - ERROR - Ошибка при обработке сообщения: name 'save_to_database_and_notify_admin' is not defined
2024-01-21 19:09:52,564 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:09:53,065 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getMe HTTP/1.1" 200 189
2024-01-21 19:09:53,068 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:09:53,549 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 353
2024-01-21 19:09:53,550 - root - ERROR - Ошибка при обработке сообщения: name 'save_to_database_and_notify_admin' is not defined
2024-01-21 19:10:13,613 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520869&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:10:14,300 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520869&timeout=20 HTTP/1.1" 200 1036
2024-01-21 19:10:14,301 - root - ERROR - Ошибка при обработке сообщения: name 'save_to_database_and_notify_admin' is not defined
2024-01-21 19:10:17,733 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:10:18,261 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getMe HTTP/1.1" 200 189
2024-01-21 19:10:18,263 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:10:38,758 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:10:58,825 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:11:18,888 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:11:38,956 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:11:59,023 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:12:19,087 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:12:39,168 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:12:59,243 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:13:19,316 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:26:46,366 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:26:46,908 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getMe HTTP/1.1" 200 189
2024-01-21 19:26:46,910 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:26:55,911 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 360
2024-01-21 19:26:55,911 - root - ERROR - Ошибка при обработке сообщения: name 'save_to_database_and_notify_admin' is not defined
2024-01-21 19:27:05,737 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520871&timeout=20 HTTP/1.1" 200 359
2024-01-21 19:27:05,737 - root - ERROR - Ошибка при обработке сообщения: name 'save_to_database_and_notify_admin' is not defined
2024-01-21 19:27:25,798 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:27:45,866 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:28:05,928 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:28:26,003 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:28:46,070 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:29:06,142 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:29:26,204 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:29:46,272 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:30:06,337 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:30:26,399 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:30:46,464 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:31:06,529 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:31:26,592 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:31:46,656 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:32:06,722 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:32:26,793 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520872&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:44:17,811 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:44:18,507 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getMe HTTP/1.1" 200 189
2024-01-21 19:44:18,508 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:44:18,987 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 353
2024-01-21 19:44:18,988 - root - ERROR - Ошибка при обработке сообщения: name 'save_to_database_and_notify_admin' is not defined
2024-01-21 19:44:39,049 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520873&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:44:50,347 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520873&timeout=20 HTTP/1.1" 200 365
2024-01-21 19:44:50,347 - root - ERROR - Ошибка при обработке сообщения: name 'save_to_database_and_notify_admin' is not defined
2024-01-21 19:45:02,884 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520874&timeout=20 HTTP/1.1" 200 371
2024-01-21 19:45:02,885 - root - ERROR - Ошибка при обработке сообщения: name 'save_to_database_and_notify_admin' is not defined
2024-01-21 19:45:22,949 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520875&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:45:43,009 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520875&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:47:40,799 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:47:41,181 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getMe HTTP/1.1" 200 189
2024-01-21 19:47:41,184 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:47:54,949 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 359
2024-01-21 19:47:54,974 - root - ERROR - Ошибка при коммите транзакции: 'sqlite3.Connection' object has no attribute 'closed'
2024-01-21 19:47:54,975 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:47:55,500 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=428167246&text=%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9+%D0%BE%D1%82%D0%B7%D1%8B%D0%B2+%D0%BE%D1%82+MaxK930+%28ID%3A+6611082589%29%3A+%D0%9E%D0%BB%D0%B2%D0%BB%D0%B2 HTTP/1.1" 200 388
2024-01-21 19:47:55,883 - root - ERROR - Ошибка при отправке электронной почты: Connection unexpectedly closed
2024-01-21 19:47:55,883 - root - ERROR - Subject: Новый отзыв от MaxK930 (ID: 6611082589)
2024-01-21 19:47:55,883 - root - ERROR - Body: Текст отзыва: Олвлв
2024-01-21 19:47:55,990 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%A1%D0%BF%D0%B0%D1%81%D0%B8%D0%B1%D0%BE+%D0%B7%D0%B0+%D0%B2%D0%B0%D1%88%D0%B5+%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B5%21&reply_parameters=%7B%22message_id%22%3A+619%7D HTTP/1.1" 200 712
2024-01-21 19:48:15,017 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520876&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:48:16,124 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520876&timeout=20 HTTP/1.1" 200 1036
2024-01-21 19:48:16,131 - root - ERROR - Ошибка при коммите транзакции: 'sqlite3.Connection' object has no attribute 'closed'
2024-01-21 19:48:16,133 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:48:16,742 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=428167246&text=%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9+%D0%BE%D1%82%D0%B7%D1%8B%D0%B2+%D0%BE%D1%82+MaxK930+%28ID%3A+6611082589%29%3A+None HTTP/1.1" 200 362
2024-01-21 19:48:16,845 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendPhoto?chat_id=428167246&photo=AgACAgIAAxkBAAICbmWtSs9B3w0wvNH52Xr9VF4E1BSNAAIq2DEbEwFoSW0k9pkxAa2XAQADAgADeQADNAQ HTTP/1.1" 200 964
2024-01-21 19:48:16,909 - root - ERROR - Ошибка при отправке электронной почты: Connection unexpectedly closed
2024-01-21 19:48:16,909 - root - ERROR - Subject: Новый отзыв от MaxK930 (ID: 6611082589)
2024-01-21 19:48:16,909 - root - ERROR - Body: Текст отзыва: None
2024-01-21 19:48:17,020 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%A1%D0%BF%D0%B0%D1%81%D0%B8%D0%B1%D0%BE+%D0%B7%D0%B0+%D0%B2%D0%B0%D1%88%D0%B5+%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B5%21&reply_parameters=%7B%22message_id%22%3A+622%7D HTTP/1.1" 200 1389
2024-01-21 19:48:25,174 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520877&timeout=20 HTTP/1.1" 200 1036
2024-01-21 19:48:25,180 - root - ERROR - Ошибка при коммите транзакции: 'sqlite3.Connection' object has no attribute 'closed'
2024-01-21 19:48:25,306 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=428167246&text=%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9+%D0%BE%D1%82%D0%B7%D1%8B%D0%B2+%D0%BE%D1%82+MaxK930+%28ID%3A+6611082589%29%3A+None HTTP/1.1" 200 362
2024-01-21 19:48:25,419 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendPhoto?chat_id=428167246&photo=AgACAgIAAxkBAAICcmWtSthM1qZapHfdmoFS_Gb5et6-AAJJ1TEberBoSWNA5iLlDfYGAQADAgADeQADNAQ HTTP/1.1" 200 964
2024-01-21 19:48:25,480 - root - ERROR - Ошибка при отправке электронной почты: Connection unexpectedly closed
2024-01-21 19:48:25,481 - root - ERROR - Subject: Новый отзыв от MaxK930 (ID: 6611082589)
2024-01-21 19:48:25,481 - root - ERROR - Body: Текст отзыва: None
2024-01-21 19:48:25,588 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%A1%D0%BF%D0%B0%D1%81%D0%B8%D0%B1%D0%BE+%D0%B7%D0%B0+%D0%B2%D0%B0%D1%88%D0%B5+%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B5%21&reply_parameters=%7B%22message_id%22%3A+626%7D HTTP/1.1" 200 1389
2024-01-21 19:50:40,995 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:50:41,363 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getMe HTTP/1.1" 200 189
2024-01-21 19:50:41,365 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:50:41,841 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 570
2024-01-21 19:50:46,676 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520879&timeout=20 HTTP/1.1" 200 570
2024-01-21 19:50:46,941 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520880&timeout=20 HTTP/1.1" 200 393
2024-01-21 19:50:46,945 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:50:47,457 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82%21+%D0%AF+%D0%B1%D0%BE%D1%82+%D0%B4%D0%BB%D1%8F+%D1%81%D0%B1%D0%BE%D1%80%D0%B0+%D0%BE%D1%82%D0%B7%D1%8B%D0%B2%D0%BE%D0%B2.+%D0%92%D1%8B%D0%B1%D0%B5%D1%80%D0%B8%D1%82%D0%B5+%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B5%3A&reply_markup=%7B%22keyboard%22%3A+%5B%5B%7B%22text%22%3A+%22%5Cu041e%5Cu0442%5Cu0437%5Cu044b%5Cu0432%22%7D%2C+%7B%22text%22%3A+%22%5Cu041f%5Cu043e%5Cu043c%5Cu043e%5Cu0449%5Cu044c%22%7D%2C+%7B%22text%22%3A+%22%5Cu041e%5Cu0442%5Cu043f%5Cu0440%5Cu0430%5Cu0432%5Cu0438%5Cu0442%5Cu044c+%5Cu0444%5Cu043e%5Cu0442%5Cu043e%22%7D%5D%2C+%5B%7B%22text%22%3A+%22%5Cu041d%5Cu0430%5Cu0441%5Cu0442%5Cu0440%5Cu043e%5Cu0439%5Cu043a%5Cu0438%22%7D%2C+%7B%22text%22%3A+%22%5Cu0421%5Cu0442%5Cu0430%5Cu0442%5Cu0438%5Cu0441%5Cu0442%5Cu0438%5Cu043a%5Cu0430%22%7D%5D%5D%2C+%22resize_keyboard%22%3A+true%7D&reply_parameters=%7B%22message_id%22%3A+630%7D HTTP/1.1" 200 866
2024-01-21 19:50:50,915 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520881&timeout=20 HTTP/1.1" 200 408
2024-01-21 19:50:51,066 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%9F%D0%BE%D0%B6%D0%B0%D0%BB%D1%83%D0%B9%D1%81%D1%82%D0%B0%2C+%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D1%8C%D1%82%D0%B5+%D0%B2%D0%B0%D1%88%D1%83+%D1%84%D0%BE%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8E.&reply_parameters=%7B%22message_id%22%3A+632%7D HTTP/1.1" 200 828
2024-01-21 19:50:55,509 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520882&timeout=20 HTTP/1.1" 200 383
2024-01-21 19:50:55,620 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B8%3A&reply_markup=%7B%22keyboard%22%3A+%5B%5B%7B%22text%22%3A+%22%5Cu041e%5Cu0442%5Cu043f%5Cu0440%5Cu0430%5Cu0432%5Cu0438%5Cu0442%5Cu044c+%5Cu043c%5Cu0435%5Cu0441%5Cu0442%5Cu043e%5Cu043f%5Cu043e%5Cu043b%5Cu043e%5Cu0436%5Cu0435%5Cu043d%5Cu0438%5Cu0435%22%2C+%22request_location%22%3A+true%7D%2C+%7B%22text%22%3A+%22%5Cu041d%5Cu0430%5Cu0437%5Cu0430%5Cu0434%22%7D%5D%5D%2C+%22resize_keyboard%22%3A+true%7D&reply_parameters=%7B%22message_id%22%3A+634%7D HTTP/1.1" 200 655
2024-01-21 19:50:59,027 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520883&timeout=20 HTTP/1.1" 200 359
2024-01-21 19:50:59,033 - root - ERROR - Ошибка при коммите транзакции: 'sqlite3.Connection' object has no attribute 'closed'
2024-01-21 19:50:59,220 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=428167246&text=%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9+%D0%BE%D1%82%D0%B7%D1%8B%D0%B2+%D0%BE%D1%82+MaxK930+%28ID%3A+6611082589%29%3A+%D0%9D%D0%B0%D0%B7%D0%B0%D0%B4 HTTP/1.1" 200 388
2024-01-21 19:50:59,279 - root - ERROR - Ошибка при отправке электронной почты: Connection unexpectedly closed
2024-01-21 19:50:59,279 - root - ERROR - Subject: Новый отзыв от MaxK930 (ID: 6611082589)
2024-01-21 19:50:59,279 - root - ERROR - Body: Текст отзыва: Назад
2024-01-21 19:50:59,401 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%A1%D0%BF%D0%B0%D1%81%D0%B8%D0%B1%D0%BE+%D0%B7%D0%B0+%D0%B2%D0%B0%D1%88%D0%B5+%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B5%21&reply_parameters=%7B%22message_id%22%3A+636%7D HTTP/1.1" 200 712
2024-01-21 19:51:19,089 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520884&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:51:39,149 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520884&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:57:01,416 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:57:01,945 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getMe HTTP/1.1" 200 189
2024-01-21 19:57:01,948 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:57:08,192 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=1&timeout=20 HTTP/1.1" 200 359
2024-01-21 19:57:08,196 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:57:08,633 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82%21+%D0%AF+%D0%B1%D0%BE%D1%82+%D0%B4%D0%BB%D1%8F+%D1%81%D0%B1%D0%BE%D1%80%D0%B0+%D0%BE%D1%82%D0%B7%D1%8B%D0%B2%D0%BE%D0%B2.+%D0%92%D1%8B%D0%B1%D0%B5%D1%80%D0%B8%D1%82%D0%B5+%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B5%3A&reply_markup=%7B%22keyboard%22%3A+%5B%5B%7B%22text%22%3A+%22%5Cu041e%5Cu0442%5Cu0437%5Cu044b%5Cu0432%22%7D%2C+%7B%22text%22%3A+%22%5Cu041f%5Cu043e%5Cu043c%5Cu043e%5Cu0449%5Cu044c%22%7D%2C+%7B%22text%22%3A+%22%5Cu041e%5Cu0442%5Cu043f%5Cu0440%5Cu0430%5Cu0432%5Cu0438%5Cu0442%5Cu044c+%5Cu0444%5Cu043e%5Cu0442%5Cu043e%22%7D%5D%2C+%5B%7B%22text%22%3A+%22%5Cu041d%5Cu0430%5Cu0441%5Cu0442%5Cu0440%5Cu043e%5Cu0439%5Cu043a%5Cu0438%22%7D%2C+%7B%22text%22%3A+%22%5Cu0421%5Cu0442%5Cu0430%5Cu0442%5Cu0438%5Cu0441%5Cu0442%5Cu0438%5Cu043a%5Cu0430%22%7D%5D%5D%2C+%22resize_keyboard%22%3A+true%7D&reply_parameters=%7B%22message_id%22%3A+639%7D HTTP/1.1" 200 832
2024-01-21 19:57:10,625 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520885&timeout=20 HTTP/1.1" 200 359
2024-01-21 19:57:10,797 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%9F%D0%BE%D0%B6%D0%B0%D0%BB%D1%83%D0%B9%D1%81%D1%82%D0%B0%2C+%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D1%8C%D1%82%D0%B5+%D1%81%D0%B2%D0%BE%D0%B9+%D0%BE%D1%82%D0%B7%D1%8B%D0%B2.&reply_parameters=%7B%22message_id%22%3A+641%7D HTTP/1.1" 200 749
2024-01-21 19:57:12,939 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520886&timeout=20 HTTP/1.1" 200 408
2024-01-21 19:57:12,943 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.telegram.org:443
2024-01-21 19:57:13,454 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%9F%D0%BE%D0%B6%D0%B0%D0%BB%D1%83%D0%B9%D1%81%D1%82%D0%B0%2C+%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D1%8C%D1%82%D0%B5+%D0%B2%D0%B0%D1%88%D1%83+%D1%84%D0%BE%D1%82%D0%BE%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D1%8E.&reply_parameters=%7B%22message_id%22%3A+643%7D HTTP/1.1" 200 828
2024-01-21 19:57:22,315 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520887&timeout=20 HTTP/1.1" 200 1040
2024-01-21 19:57:22,322 - root - ERROR - Ошибка при коммите транзакции: 'sqlite3.Connection' object has no attribute 'closed'
2024-01-21 19:57:22,467 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=428167246&text=%D0%9D%D0%BE%D0%B2%D1%8B%D0%B9+%D0%BE%D1%82%D0%B7%D1%8B%D0%B2+%D0%BE%D1%82+MaxK930+%28ID%3A+6611082589%29%3A+None HTTP/1.1" 200 362
2024-01-21 19:57:22,664 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendPhoto?chat_id=428167246&photo=AgACAgIAAxkBAAIChWWtTPHZVSsRmQABv0ATfmMV0TG1JgACtNcxGxMBaElYqCF00HbEGgEAAwIAA3kAAzQE HTTP/1.1" 200 964
2024-01-21 19:57:22,727 - root - ERROR - Ошибка при отправке электронной почты: Connection unexpectedly closed
2024-01-21 19:57:22,727 - root - ERROR - Subject: Новый отзыв от MaxK930 (ID: 6611082589)
2024-01-21 19:57:22,728 - root - ERROR - Body: Текст отзыва: None
2024-01-21 19:57:22,918 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%A1%D0%BF%D0%B0%D1%81%D0%B8%D0%B1%D0%BE+%D0%B7%D0%B0+%D0%B2%D0%B0%D1%88%D0%B5+%D1%81%D0%BE%D0%BE%D0%B1%D1%89%D0%B5%D0%BD%D0%B8%D0%B5%21&reply_parameters=%7B%22message_id%22%3A+645%7D HTTP/1.1" 200 1393
2024-01-21 19:57:25,679 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520888&timeout=20 HTTP/1.1" 200 365
2024-01-21 19:57:25,806 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%97%D0%B4%D0%B5%D1%81%D1%8C+%D0%B2%D1%8B+%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%D0%B5+%D0%BE%D1%81%D1%82%D0%B0%D0%B2%D0%B8%D1%82%D1%8C+%D0%BE%D1%82%D0%B7%D1%8B%D0%B2+%D0%B8%D0%BB%D0%B8+%D1%83%D0%B7%D0%BD%D0%B0%D1%82%D1%8C+%D0%BE+%D0%B1%D0%BE%D1%82%D0%B5.&reply_parameters=%7B%22message_id%22%3A+649%7D HTTP/1.1" 200 831
2024-01-21 19:57:33,757 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520889&timeout=20 HTTP/1.1" 200 389
2024-01-21 19:57:33,759 - root - ERROR - Ошибка при коммите транзакции: 'sqlite3.Connection' object has no attribute 'closed'
2024-01-21 19:57:33,877 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "POST /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/sendMessage?chat_id=6611082589&text=%D0%9E%D0%B1%D1%89%D0%B5%D0%B5+%D0%BA%D0%BE%D0%BB%D0%B8%D1%87%D0%B5%D1%81%D1%82%D0%B2%D0%BE+%D0%BE%D1%82%D0%B7%D1%8B%D0%B2%D0%BE%D0%B2%3A+3&reply_parameters=%7B%22message_id%22%3A+651%7D HTTP/1.1" 200 743
2024-01-21 19:57:53,825 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520890&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:58:13,887 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520890&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:58:33,949 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520890&timeout=20 HTTP/1.1" 200 23
2024-01-21 19:58:54,022 - urllib3.connectionpool - DEBUG - https://api.telegram.org:443 "GET /bot6809168718:AAHu0neOmPosOZAQKmdfYQpFABBc8jV2HuI/getUpdates?offset=734520890&timeout=20 HTTP/1.1" 200 23
